# Generated by Django 6.0.4 on 2026-04-20 22:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("item", "0002_alter_category_options_items"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Items",
            new_name="Item",
        ),
    ]
